export const filterOptions = {
    types: [
      '',
      'Normal',
      'Fire',
      'Water',
      'Electric',
      'Grass',
      'Ice',
      'Fighting',
      'Poison',
      'Ground',
      'Flying',
      'Psychic',
      'Bug',
      'Rock',
      'Ghost',
      'Dragon',
      'Dark',
      'Steel',
      'Fairy',
    ],
    weights: [
      '',
      'Lighter than 10 kg',
      'Between 10 kg and 25 kg',
      'Between 25 kg and 50 kg',
      'Between 50 kg and 100 kg',
      'Heavier than 100 kg',
    ],
    moves: [
      'Tackle',
      'Tail Whip',
      'Growl',
      'Ember',
      'Water Gun',
      'Thunder Shock',
      'Quick Attack',
      'Vine Whip',
      'Ice Shard',
      'Karate Chop',
      'Poison Sting',
      'Earthquake',
      'Fly',
      'Psychic',
      'Pin Missile',
      'Rock Throw',
      'Shadow Ball',
      'Dragon Claw',
      'Dazzling Gleam',
    ],
  };
  